/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorDashboardRouteImport } from './routes/vendor-dashboard'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as StandardBookingRouteImport } from './routes/standard-booking'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiderDashboardRouteImport } from './routes/rider-dashboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as ParkWaybillRouteImport } from './routes/park-waybill'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminVendorsRouteImport } from './routes/admin-vendors'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'

const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor-dashboard',
  path: '/vendor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardBookingRoute = StandardBookingRouteImport.update({
  id: '/standard-booking',
  path: '/standard-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderDashboardRoute = RiderDashboardRouteImport.update({
  id: '/rider-dashboard',
  path: '/rider-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkWaybillRoute = ParkWaybillRouteImport.update({
  id: '/park-waybill',
  path: '/park-waybill',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin-vendors',
  path: '/admin-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/park-waybill': typeof ParkWaybillRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/rider-dashboard': typeof RiderDashboardRoute
  '/signup': typeof SignupRoute
  '/standard-booking': typeof StandardBookingRoute
  '/stocks': typeof StocksRoute
  '/terms': typeof TermsRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/me': typeof AuthenticatedMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/park-waybill': typeof ParkWaybillRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/rider-dashboard': typeof RiderDashboardRoute
  '/signup': typeof SignupRoute
  '/standard-booking': typeof StandardBookingRoute
  '/stocks': typeof StocksRoute
  '/terms': typeof TermsRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/me': typeof AuthenticatedMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/park-waybill': typeof ParkWaybillRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/rider-dashboard': typeof RiderDashboardRoute
  '/signup': typeof SignupRoute
  '/standard-booking': typeof StandardBookingRoute
  '/stocks': typeof StocksRoute
  '/terms': typeof TermsRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-vendors'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/marketplace'
    | '/park-waybill'
    | '/pending-approval'
    | '/privacy'
    | '/rider-dashboard'
    | '/signup'
    | '/standard-booking'
    | '/stocks'
    | '/terms'
    | '/vendor-dashboard'
    | '/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-vendors'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/marketplace'
    | '/park-waybill'
    | '/pending-approval'
    | '/privacy'
    | '/rider-dashboard'
    | '/signup'
    | '/standard-booking'
    | '/stocks'
    | '/terms'
    | '/vendor-dashboard'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-vendors'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/marketplace'
    | '/park-waybill'
    | '/pending-approval'
    | '/privacy'
    | '/rider-dashboard'
    | '/signup'
    | '/standard-booking'
    | '/stocks'
    | '/terms'
    | '/vendor-dashboard'
    | '/_authenticated/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ParkWaybillRoute: typeof ParkWaybillRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PrivacyRoute: typeof PrivacyRoute
  RiderDashboardRoute: typeof RiderDashboardRoute
  SignupRoute: typeof SignupRoute
  StandardBookingRoute: typeof StandardBookingRoute
  StocksRoute: typeof StocksRoute
  TermsRoute: typeof TermsRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-dashboard': {
      id: '/vendor-dashboard'
      path: '/vendor-dashboard'
      fullPath: '/vendor-dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard-booking': {
      id: '/standard-booking'
      path: '/standard-booking'
      fullPath: '/standard-booking'
      preLoaderRoute: typeof StandardBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider-dashboard': {
      id: '/rider-dashboard'
      path: '/rider-dashboard'
      fullPath: '/rider-dashboard'
      preLoaderRoute: typeof RiderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park-waybill': {
      id: '/park-waybill'
      path: '/park-waybill'
      fullPath: '/park-waybill'
      preLoaderRoute: typeof ParkWaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-vendors': {
      id: '/admin-vendors'
      path: '/admin-vendors'
      fullPath: '/admin-vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  ParkWaybillRoute: ParkWaybillRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PrivacyRoute: PrivacyRoute,
  RiderDashboardRoute: RiderDashboardRoute,
  SignupRoute: SignupRoute,
  StandardBookingRoute: StandardBookingRoute,
  StocksRoute: StocksRoute,
  TermsRoute: TermsRoute,
  VendorDashboardRoute: VendorDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
