/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthenticatedVendorDashboardRouteImport } from './routes/_authenticated/vendor-dashboard'
import { Route as AuthenticatedStocksRouteImport } from './routes/_authenticated/stocks'
import { Route as AuthenticatedStandardBookingRouteImport } from './routes/_authenticated/standard-booking'
import { Route as AuthenticatedRiderDashboardRouteImport } from './routes/_authenticated/rider-dashboard'
import { Route as AuthenticatedParkWaybillRouteImport } from './routes/_authenticated/park-waybill'
import { Route as AuthenticatedMarketplaceCheckoutRouteImport } from './routes/_authenticated/marketplace-checkout'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin-vendors'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorDashboardRoute =
  AuthenticatedVendorDashboardRouteImport.update({
    id: '/vendor-dashboard',
    path: '/vendor-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStocksRoute = AuthenticatedStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStandardBookingRoute =
  AuthenticatedStandardBookingRouteImport.update({
    id: '/standard-booking',
    path: '/standard-booking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiderDashboardRoute =
  AuthenticatedRiderDashboardRouteImport.update({
    id: '/rider-dashboard',
    path: '/rider-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParkWaybillRoute =
  AuthenticatedParkWaybillRouteImport.update({
    id: '/park-waybill',
    path: '/park-waybill',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceCheckoutRoute =
  AuthenticatedMarketplaceCheckoutRouteImport.update({
    id: '/marketplace-checkout',
    path: '/marketplace-checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/admin-vendors',
    path: '/admin-vendors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-vendors': typeof AuthenticatedAdminVendorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/marketplace-checkout': typeof AuthenticatedMarketplaceCheckoutRoute
  '/park-waybill': typeof AuthenticatedParkWaybillRoute
  '/rider-dashboard': typeof AuthenticatedRiderDashboardRoute
  '/standard-booking': typeof AuthenticatedStandardBookingRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/vendor-dashboard': typeof AuthenticatedVendorDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-vendors': typeof AuthenticatedAdminVendorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/marketplace-checkout': typeof AuthenticatedMarketplaceCheckoutRoute
  '/park-waybill': typeof AuthenticatedParkWaybillRoute
  '/rider-dashboard': typeof AuthenticatedRiderDashboardRoute
  '/standard-booking': typeof AuthenticatedStandardBookingRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/vendor-dashboard': typeof AuthenticatedVendorDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/marketplace-checkout': typeof AuthenticatedMarketplaceCheckoutRoute
  '/_authenticated/park-waybill': typeof AuthenticatedParkWaybillRoute
  '/_authenticated/rider-dashboard': typeof AuthenticatedRiderDashboardRoute
  '/_authenticated/standard-booking': typeof AuthenticatedStandardBookingRoute
  '/_authenticated/stocks': typeof AuthenticatedStocksRoute
  '/_authenticated/vendor-dashboard': typeof AuthenticatedVendorDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/admin-vendors'
    | '/dashboard'
    | '/history'
    | '/marketplace'
    | '/marketplace-checkout'
    | '/park-waybill'
    | '/rider-dashboard'
    | '/standard-booking'
    | '/stocks'
    | '/vendor-dashboard'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/admin-vendors'
    | '/dashboard'
    | '/history'
    | '/marketplace'
    | '/marketplace-checkout'
    | '/park-waybill'
    | '/rider-dashboard'
    | '/standard-booking'
    | '/stocks'
    | '/vendor-dashboard'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/admin-vendors'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/marketplace'
    | '/_authenticated/marketplace-checkout'
    | '/_authenticated/park-waybill'
    | '/_authenticated/rider-dashboard'
    | '/_authenticated/standard-booking'
    | '/_authenticated/stocks'
    | '/_authenticated/vendor-dashboard'
    | '/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor-dashboard': {
      id: '/_authenticated/vendor-dashboard'
      path: '/vendor-dashboard'
      fullPath: '/vendor-dashboard'
      preLoaderRoute: typeof AuthenticatedVendorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stocks': {
      id: '/_authenticated/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedStocksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standard-booking': {
      id: '/_authenticated/standard-booking'
      path: '/standard-booking'
      fullPath: '/standard-booking'
      preLoaderRoute: typeof AuthenticatedStandardBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider-dashboard': {
      id: '/_authenticated/rider-dashboard'
      path: '/rider-dashboard'
      fullPath: '/rider-dashboard'
      preLoaderRoute: typeof AuthenticatedRiderDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/park-waybill': {
      id: '/_authenticated/park-waybill'
      path: '/park-waybill'
      fullPath: '/park-waybill'
      preLoaderRoute: typeof AuthenticatedParkWaybillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace-checkout': {
      id: '/_authenticated/marketplace-checkout'
      path: '/marketplace-checkout'
      fullPath: '/marketplace-checkout'
      preLoaderRoute: typeof AuthenticatedMarketplaceCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-vendors': {
      id: '/_authenticated/admin-vendors'
      path: '/admin-vendors'
      fullPath: '/admin-vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMarketplaceCheckoutRoute: typeof AuthenticatedMarketplaceCheckoutRoute
  AuthenticatedParkWaybillRoute: typeof AuthenticatedParkWaybillRoute
  AuthenticatedRiderDashboardRoute: typeof AuthenticatedRiderDashboardRoute
  AuthenticatedStandardBookingRoute: typeof AuthenticatedStandardBookingRoute
  AuthenticatedStocksRoute: typeof AuthenticatedStocksRoute
  AuthenticatedVendorDashboardRoute: typeof AuthenticatedVendorDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMarketplaceCheckoutRoute: AuthenticatedMarketplaceCheckoutRoute,
  AuthenticatedParkWaybillRoute: AuthenticatedParkWaybillRoute,
  AuthenticatedRiderDashboardRoute: AuthenticatedRiderDashboardRoute,
  AuthenticatedStandardBookingRoute: AuthenticatedStandardBookingRoute,
  AuthenticatedStocksRoute: AuthenticatedStocksRoute,
  AuthenticatedVendorDashboardRoute: AuthenticatedVendorDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
